var LOCALIZE = function(){ return {
'getCurrency' : function(){ return 'KRW'; },
'getCurrencyChar' : function(){ return '￦'; },
'getCurrencyDecimalCount' : function(){ return 0; },
'getCurrencyDecimalChar' : function(){ return '.'; },
'getCurrencyThousandChar' : function(){ return ','; },
'getCurrencyFormat' : function(price){ return money_format(price)+'원';  },
'convArguments' : function(){ var msg=arguments[0]; if (arguments[1].length>0){ for(var i=1; i<=arguments[1].length; i++) msg = msg.replace('%'+i, arguments[1][i-1]);}; return msg; },
'설명_선택한항목이없습니다' : function(){ return LOCALIZE.convArguments("선택한 항목이 없습니다", arguments); },
'설명_작성권한이없습니다' : function(){ return LOCALIZE.convArguments("작성 권한이 없습니다.", arguments); },
'버튼_더보기' : function(){ return LOCALIZE.convArguments("더보기", arguments); },
'설명_로그인이_필요합니다' : function(){ return LOCALIZE.convArguments("로그인이 필요합니다.", arguments); },
'설명_내용을_입력해주세요' : function(){ return LOCALIZE.convArguments("내용을 입력해주세요", arguments); },
'설명_삭제된_댓글_입니다' : function(){ return LOCALIZE.convArguments("삭제된 댓글 입니다.", arguments); },
'설명_비밀번호' : function(){ return LOCALIZE.convArguments("비밀번호", arguments); },
'타이틀_수량' : function(){ return LOCALIZE.convArguments("수량", arguments); },
'설명_장바구니가비어있습니다' : function(){ return LOCALIZE.convArguments("장바구니가 비어있습니다.", arguments); },
'타이틀_총수량' : function(){ return LOCALIZE.convArguments("총수량 <em class=\"text-brand\">%1</em>개", arguments); },
'타이틀_총금액' : function(){ return LOCALIZE.convArguments("총금액 %1", arguments); },
'설명_이미선택된옵션입니다' : function(){ return LOCALIZE.convArguments("이미 선택된 옵션입니다", arguments); },
'설명_택배사또는송장번호가입력되지않았습니다' : function(){ return LOCALIZE.convArguments("택배사 또는 송장번호가 입력되지 않았습니다.", arguments); },
'설명_택배사배송정보가업데이트중이거나정보가정확하지않습니다' : function(){ return LOCALIZE.convArguments("택배사 배송정보가 업데이트 중이거나 정보가 정확하지 않습니다.", arguments); },
'버튼_응답수정' : function(){ return LOCALIZE.convArguments("응답 수정", arguments); },
'설명_개인정보처리방침에동의하여주시기바랍니다' : function(){ return LOCALIZE.convArguments("개인정보 수집 및 이용에 동의하여 주시기 바랍니다.", arguments); },
'설명_필수항목을입력하여주시기바랍니다' : function(){ return LOCALIZE.convArguments("필수 항목을 입력하여 주시기 바랍니다.", arguments); },
'버튼_확인닫기' : function(){ return LOCALIZE.convArguments("확인", arguments); },
'버튼_메뉴더보기' : function(){ return LOCALIZE.convArguments("더보기", arguments); },
'설명_잘못된접근입니다' : function(){ return LOCALIZE.convArguments("잘못된 접근입니다.", arguments); },
'버튼_카카오톡' : function(){ return LOCALIZE.convArguments("카카오톡", arguments); },
'버튼_카카오스토리' : function(){ return LOCALIZE.convArguments("카카오스토리", arguments); },
'버튼_라인' : function(){ return LOCALIZE.convArguments("라인", arguments); },
'버튼_밴드' : function(){ return LOCALIZE.convArguments("밴드", arguments); },
'버튼_페이스북' : function(){ return LOCALIZE.convArguments("페이스북", arguments); },
'버튼_트위터' : function(){ return LOCALIZE.convArguments("트위터", arguments); },
'버튼_인스타그램' : function(){ return LOCALIZE.convArguments("인스타그램", arguments); },
'버튼_공유하기' : function(){ return LOCALIZE.convArguments("공유하기", arguments); },
'설명_카카오톡공유는모바일에서만지원합니다' : function(){ return LOCALIZE.convArguments("카카오톡 공유는 모바일에서만 지원합니다", arguments); },
'설명_라인공유는모바일에서만지원합니다' : function(){ return LOCALIZE.convArguments("라인공유는 모바일에서만 지원합니다", arguments); },
'설명_수량' : function(){ return LOCALIZE.convArguments("수량", arguments); },
'설명_주문자이름을입력해주세요' : function(){ return LOCALIZE.convArguments("주문자 이름을 입력해주세요", arguments); },
'설명_주문자연락처를입력해주세요' : function(){ return LOCALIZE.convArguments("주문자 연락처를 입력해주세요", arguments); },
'설명_이메일을입력해주세요' : function(){ return LOCALIZE.convArguments("이메일을 입력해주세요", arguments); },
'설명_배송지이름을입력해주세요' : function(){ return LOCALIZE.convArguments("배송지 이름을 입력해주세요", arguments); },
'설명_배송지연락처를입력해주세요' : function(){ return LOCALIZE.convArguments("배송지 연락처를 입력해주세요", arguments); },
'설명_개인통관고유부호를입력해주세요' : function(){ return LOCALIZE.convArguments("개인통관고유부호를 입력해주세요", arguments); },
'설명_배송지주소를입력해주세요' : function(){ return LOCALIZE.convArguments("배송지 주소를 입력해주세요", arguments); },
'설명_배송지주소City를입력해주세요' : function(){ return LOCALIZE.convArguments("배송지 주소 (City) 를 입력해주세요", arguments); },
'설명_배송지주소State를입력해주세요' : function(){ return LOCALIZE.convArguments("배송지 주소 (State) 를 입력해주세요", arguments); },
'설명_배송지주소Building를입력해주세요' : function(){ return LOCALIZE.convArguments("배송지 주소 (Building) 를 입력해주세요", arguments); },
'설명_배송지주소Street를입력해주세요' : function(){ return LOCALIZE.convArguments("배송지 주소 (Street) 를 입력해주세요", arguments); },
'설명_배송지주소ZipCode를입력해주세요' : function(){ return LOCALIZE.convArguments("배송지 주소 (Zip Code)를 입력해주세요", arguments); },
'설명_가입되어있지않습니다' : function(){ return LOCALIZE.convArguments("가입되어 있지 않습니다", arguments); },
'설명_생성된그룹이없습니다' : function(){ return LOCALIZE.convArguments("생성된 그룹이 없습니다", arguments); },
'설명_거리순정렬이지원되지않습니다' : function(){ return LOCALIZE.convArguments("거리순 정렬이 지원되지 않습니다", arguments); },
'버튼_상세보기' : function(){ return LOCALIZE.convArguments("상세보기", arguments); },
'설명_이미신청중입니다잠시후다시시도하여주시기바랍니다' : function(){ return LOCALIZE.convArguments("이미 신청중입니다. 잠시후 다시 시도하여 주시기 바랍니다.", arguments); },
'설명_비밀번호변경이완료되었습니다' : function(){ return LOCALIZE.convArguments("비밀번호 변경이 완료되었습니다", arguments); },
'설명_동일한암호로입력하시기바랍니다' : function(){ return LOCALIZE.convArguments("동일한 암호로 입력하시기 바랍니다.", arguments); },
'설명_정상적인암호로입력하시기바랍니다' : function(){ return LOCALIZE.convArguments("정상적인 암호로 입력하시기 바랍니다.(8자이상)", arguments); },
'설명_변경가능시간을초과하였습니다' : function(){ return LOCALIZE.convArguments("변경 가능 시간을 초과 하였습니다.", arguments); },
'설명_동의해주세요' : function(){ return LOCALIZE.convArguments("동의해 주세요", arguments); },
'설명_주소를입력하세요' : function(){ return LOCALIZE.convArguments("주소를 입력하세요", arguments); },
'설명_가입승인이필요합니다' : function(){ return LOCALIZE.convArguments("가입승인이 필요합니다.", arguments); },
'설명_주소장소를검색해주세요' : function(){ return LOCALIZE.convArguments("주소, 장소를 검색 해주세요.", arguments); },
'설명_주소검색버튼을눌러주세요' : function(){ return LOCALIZE.convArguments("주소검색 버튼을 눌러서 등록해 주세요.", arguments); },
'설명_검색결과가존재하지않습니다' : function(){ return LOCALIZE.convArguments("검색 결과가 존재하지 않습니다.", arguments); },
'설명_삭제하시겠습니까' : function(){ return LOCALIZE.convArguments("삭제하시겠습니까?", arguments); },
'설명_위치정보검색에문제가있습니다' : function(){ return LOCALIZE.convArguments("위치정보 검색에 문제가 있습니다.", arguments); },
'설명_위치정보검색을허용해주세요' : function(){ return LOCALIZE.convArguments("위치정보 검색을 허용해주세요.", arguments); },
'설명_위치정보를검색하지못했습니다' : function(){ return LOCALIZE.convArguments("위치정보를 검색하지 못했습니다.위치정보 수집기능을 작동시켜주세요", arguments); },
'설명_위치정보검색시간을초과하였습니다' : function(){ return LOCALIZE.convArguments("위치정보 검색 시간을 초과하였습니다.", arguments); },
'설명_위치검색이지원되지않는브라우져입니다' : function(){ return LOCALIZE.convArguments("위치검색이 지원되지 않는 브라우져입니다.", arguments); },
'설명_작성시등록하신비밀번호를입력해주세요' : function(){ return LOCALIZE.convArguments("작성시 등록하신 비밀번호를 입력해주세요.", arguments); },
'설명_테스트결제메시지' : function(){ return LOCALIZE.convArguments("현재 테스트 결제 상태입니다.\n테스트 결제에서는 주문하더라도 실제 과금되지 않으며 실제 주문되진 않습니다.", arguments); },
'설명_접근권한이없습니다' : function(){ return LOCALIZE.convArguments("접근 권한이 없습니다", arguments); },
'설명_최대업로드용량안내' : function(){ return LOCALIZE.convArguments("최대 50MB 까지 업로드 하실 수 있습니다.", arguments); },
'설명_네이버페이찜등록실패' : function(){ return LOCALIZE.convArguments("네이버페이 찜등록 실패 (%1)", arguments); },
'설명_네이버페이상품구매실패' : function(){ return LOCALIZE.convArguments("네이버페이 상품 구매 실패 (%1)", arguments); },
'설명_성공' : function(){ return LOCALIZE.convArguments("성공", arguments); },
'설명_취소되었습니다' : function(){ return LOCALIZE.convArguments("취소 되었습니다.", arguments); },
'설명_취소요청이접수되었습니다' : function(){ return LOCALIZE.convArguments("취소요청이 접수 되었습니다.", arguments); },
'타이틀_대표이미지설정' : function(){ return LOCALIZE.convArguments("대표 이미지 설정", arguments); },
'설명_첨부된이미지가없습니다' : function(){ return LOCALIZE.convArguments("첨부된 이미지가 없습니다.", arguments); },
'설명_오전' : function(){ return LOCALIZE.convArguments("오전", arguments); },
'설명_오후' : function(){ return LOCALIZE.convArguments("오후", arguments); },
'설명_페이지를벗어나시겠습니까' : function(){ return LOCALIZE.convArguments("이 페이지를 벗어나시겠습니까?", arguments); },
'설명_테스트결제메시지_이니시스' : function(){ return LOCALIZE.convArguments("현재 테스트 결제 상태입니다.\nKG 이니시스의 경우엔 주문 하신 후 일정시간이 지나면 자동으로 취소 처리가 됩니다.", arguments); },
'설명_주문하실상품을선택해주세요' : function(){ return LOCALIZE.convArguments("주문하실 상품을 선택해 주세요.", arguments); },
'버튼_네이버' : function(){ return LOCALIZE.convArguments("네이버", arguments); },
'설명_네이버페이를계속해서진행하시겠습니까' : function(){ return LOCALIZE.convArguments("N페이 결제를 계속해서 진행하시겠습니까?", arguments); },

}}();